#! /bin/bash
# Deploy only if it's not a pull request
if [ -z "$TRAVIS_PULL_REQUEST" ] || [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  if [ "$TRAVIS_BRANCH" == "dev" ]; then
      echo "Deploying $TRAVIS_BRANCH on $SERVICE_DEV (tag: $REPO:$TAG)"
      ./ecs-deploy -n $SERVICE_DEV -c $CLUSTER_DEV -i $REPO:$TAG -r $AWS_REGION -k $AWS_ECS_DEV_DEPLOYER_ACCESS_KEY_ID -s $AWS_ECS_DEV_DEPLOYER_SECRET_ACCESS_KEY
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Deploying $TRAVIS_BRANCH on $SERVICE_PROD (tag: $REPO:$TAG)"
      ./ecs-deploy -n $SERVICE_PROD -c $CLUSTER_PROD -i $REPO:$TAG -r $AWS_REGION -k $AWS_ECS_PROD_DEPLOYER_ACCESS_KEY_ID -s $AWS_ECS_PROD_DEPLOYER_SECRET_ACCESS_KEY
    fi
else
  echo "Skipping deploy because it's a PR"
fi
